# Generated by Django 3.0.14 on 2021-07-20 11:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionPredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='unknown', max_length=256, null=True)),
                ('predict', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
