# Generated by Django 3.0.14 on 2021-07-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionpredictionmodel',
            old_name='predict',
            new_name='prediction',
        ),
    ]
